services:
  # Backend API Service
  - type: web
    name: ticket-manager-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py

  # Frontend Static Site
  - type: static
    name: ticket-manager-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PUBLIC_API_URL
        value: https://ticket-manager-api.onrender.com

  # File Storage (Redis for session data)
  - type: redis
    name: ticket-manager-cache
    plan: free
    maxmemoryPolicy: allkeys-lru