version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - NODE_ENV=development
    command: sleep infinity
    networks:
      - ticket-mgr-network
    ports:
      - "4321:4321"  # Astro dev server
      - "5001:5000"  # Flask API server

networks:
  ticket-mgr-network:
    driver: bridge